### ISSUE TITLE
Credit Card Brand Image not showing

### ISSUE THREAD

**Issue by otymartin** [orazz/CreditCardForm-iOS#11]
@orazz 
I just implemented this following the demo example.

The brand colors change accordingly however the chip and brand images dont show.

Secondary question: How can I display an existing card with the branded card image and not the default black view?
![15991670_10158052853890608_1723324319_o](https://cloud.githubusercontent.com/assets/2222881/21834603/6103cc76-d784-11e6-8fb8-c01405de4e7b.jpg)

**Comment by orazz** [comment]
Update to latest version and check again

**Comment by orazz** [comment]
Instead colour do you want show brand card image?

**Comment by otymartin** [comment]
@orazz Yes i thought the default behavior was a chip on the top left and brand logo on top right. Im using the latest version.

**Comment by orazz** [comment]
Check it out. I updated (0.1.0)

**Comment by otymartin** [comment]
@orazz beautiful its working now :)

**Comment by JohnyKumar27** [comment]
Getting same issue bro, Can you help me...

**Comment by varunmehta77** [comment]
I am also fetching same issue. No brand image and no chip image.

**Comment by orazz** [comment]
Check it out. I updated [(0.1.1)](https://github.com/orazz/CreditCardForm-iOS/releases/tag/0.1.1)

**Comment by agung-s** [comment]
Hey orazz, 

I think I still got this issue, any idea why?

**Comment by AndreVicenteW** [comment]
Any news about it?

**Comment by orazz** [comment]
@agung-s , @AndreVicenteW 
please provide more information which pod release a u using?

CreditCardForm (0.1.8)
Stripe (13.2.0)

![untitled](https://user-images.githubusercontent.com/8214953/46035169-dd8bbb00-c11b-11e8-9357-4fc325c8cf45.gif)

**Comment by pethumishara** [comment]
Im also facing same issue.

**Comment by ludivinefafournoux** [comment]
Hi, I have this issue too with CreditCardForm (0.1.9)
