### ISSUE TITLE
CardHolder placeholder editable

### ISSUE THREAD

**Issue by ramses-bemobile** [orazz/CreditCardForm-iOS#13]
Hi, 

can you please add the possibility to edit de cardholder placeholder text? 

Like the expiry text. 

    @IBInspectable
    public var expireDatePlaceholderText = "EXPIRY" {
        didSet {
            expireDateText.text = expireDatePlaceholderText
        }
    }

Thanks

**Comment by orazz** [comment]
creditCardView.cardHolderPlaceholderString = "Card Placeholder"

[support version 0.1.1](https://github.com/orazz/CreditCardForm-iOS/releases/tag/0.1.1)
