### ISSUE TITLE
Stripe

### ISSUE THREAD

**Issue by gomitaana** [orazz/CreditCardForm-iOS#14]
It´s possible to use it without Stripe?

**Comment by patchthecode** [comment]
i am going to use this together with stripe

**Comment by ErShreyansh12** [comment]
Waiting for library to use without stripe. Because in my application, different payment gateway used. And only for this i need to install pod of stripe and too many files are added in project.

**Comment by blinkuz** [comment]
I also needed to use this pod but without stripe since I am interested only in the visual part for the management of the credit card, if it were possible to integrate it without a stripe, please give me some reference link.

**Comment by orazz** [comment]
> Waiting for library to use without stripe. Because in my application, different payment gateway used. And only for this i need to install pod of stripe and too many files are added in project.

You don't have to install Stripe.
If you're using different payment gateway just implement delegate for your textfield and in textDidChange method put this code:
```
creditCardForm.paymentCardTextFieldDidChange(cardNumber: textField.cardNumber, expirationYear: textField.expirationYear, expirationMonth: textField.expirationMonth, cvc: textField.cvc)
```
for expire year:
```
creditCardForm.paymentCardTextFieldDidEndEditingExpiration(expirationYear: textField.expirationYear)
```
cvc field did begin editing
```
creditCardForm.paymentCardTextFieldDidBeginEditingCVC()
```

cvc field did end editing
```
 creditCardForm.paymentCardTextFieldDidEndEditingCVC()
```
