### ISSUE TITLE
How i can set value for paymentTextField?

### ISSUE THREAD

**Issue by mhtranbn** [orazz/CreditCardForm-iOS#16]
Hi @orazz , how i can set text for this paymentTextField of great **CreditCardForm-iOS** ? Many thank for  support !

**Comment by orazz** [comment]
Did you try use demo app?

**Comment by mhtranbn** [comment]
i had try both use demo, it only can get value of paymentTextField.cardnumber, i cant not set value for paymentTextField.cardnumber. @orazz  many thank for support sir.

**Comment by orazz** [comment]
Why do you want to set value to paymentTextField?

**Comment by mhtranbn** [comment]
Becaue we need edit card information (Example: Exp of card), then user only need change number exp. Many thank for support @orazz .

**Comment by orazz** [comment]
I used stripe for payment and stripe aren't allowed to set cardnumber (paymentTextField), but you can save card details to charge it later.

**Comment by abhishekNebQuovantis** [comment]
I think the above functionality will be very useful while scanning credit card details and setting the same in textfield. What's your opinion regarding same?

**Comment by orazz** [comment]
@abhishekNebQuovantis it would be great!

**Comment by KevinJue** [comment]
any news about this feature ?

**Comment by KevinJue** [comment]
According to stripe documentation you can do it. 

```
STPCardParams *cardParams = [[STPCardParams alloc] init];
cardParams.number = @"4242424242424242";
cardParams.expMonth = 10;
cardParams.expYear = 2018;
cardParams.cvc = @"123";
```

then apply this to your STPPaymentCardTextField.cardParams

**Comment by orazz** [comment]
Are you familiar with the concept [PCI](https://www.google.co.uk/search?q=pci&ie=utf-8&oe=utf-8&client=firefox-b&gfe_rd=cr&ei=fG4qWaetBIKDaL-MgbAH)?
