### ISSUE TITLE
Got error when implementing UITableVIewController. Using static table

### ISSUE THREAD

**Issue by zahedul** [orazz/CreditCardForm-iOS#22]
Terminating app due to uncaught exception 'NSGenericException', reason: 'Unable to activate constraint with anchors <NSLayoutXAxisAnchor:0x60400067aa40 "STPPaymentCardTextField:0x7fcf9b413d00.centerX"> and <NSLayoutXAxisAnchor:0x60400067a9c0 "UITableView:0x7fcf9b824000.centerX"> because they have no common ancestor.  Does the constraint or its anchors reference items in different view hierarchies?  That's illegal.'

**Comment by orazz** [comment]
Do you have a sample project you can send me?

**Comment by zahedul** [comment]
It fixed.
I have change 
```
paymentTextField.frame = CGRect(x: 15, y: 199, width: self.view.frame.size.width - 30, height: 44)
```
to
```
paymentTextField.frame = CGRect(x: 15, y: 199, width: self.containerView.frame.size.width - 30, height: 44)
```
`containerView` is the tableCell container view

change also 
```
paymentTextField.centerXAnchor.constraint(equalTo: view.centerXAnchor),
```
to 
```
paymentTextField.centerXAnchor.constraint(equalTo: containerView.centerXAnchor),
```
