### ISSUE TITLE
Deprecation Warnings

### ISSUE THREAD

**Issue by eciftcioglu** [orazz/CreditCardForm-iOS#24]
Hi.After the swift 4 update alot of deprecation warnings appeared. Are you still maintaining this library?Thanks for the help beforehand.

![screen shot 2017-11-06 at 16 45 14 2](https://user-images.githubusercontent.com/11834123/32444115-121cb696-c30a-11e7-85f5-642c976bc0c2.png)

**Comment by orazz** [comment]
[Fixed version 0.1.4](https://github.com/orazz/CreditCardForm-iOS/releases/tag/0.1.4)
