### ISSUE TITLE
Error:AKMaskFieldUtility.swift:43:12: Subscripts returning String were obsoleted in Swift 4

### ISSUE THREAD

**Issue by eciftcioglu** [orazz/CreditCardForm-iOS#25]
I'm getting this error after downloading version 0.1.5. Am I missing something. Thanks for the help beforehand.

<img width="1280" alt="screen shot 2017-11-12 at 15 51 08" src="https://user-images.githubusercontent.com/11834123/32699129-31194718-c7b9-11e7-9096-68f64e3a7fb8.png">

**Comment by orazz** [comment]
XCode 9, Build test: Succeeded
![screen shot 2017-11-13 at 3 53 41 pm](https://user-images.githubusercontent.com/8214953/32722177-dbfdb2c8-c88a-11e7-9d62-d5cdf5fe8ca9.png)
