### ISSUE TITLE
Format weird on AMEX Card

### ISSUE THREAD

**Issue by croossin** [orazz/CreditCardForm-iOS#27]
It seems that there is an extra * on AMEX cards.  Also, the CVV field only allows for 3 digits for these cards, which on AMEX, is normally 4 digits.

![img_82cb903db795-1](https://user-images.githubusercontent.com/7241069/34306696-60475124-e6f9-11e7-9336-e3f707a4c83b.jpeg)

**Comment by croossin** [comment]
Any luck with this?

**Comment by orazz** [comment]
Fixed
