### ISSUE TITLE
[Crash][0.1.5] Inserting cvc only crashes the form

### ISSUE THREAD

**Issue by airspeed** [orazz/CreditCardForm-iOS#28]
**Steps to reproduce:**
1. Start CreditCardForm UI
2. Skip card number and expiration date
3. Edit cvc

**Expected:**
The text in the cvc text field reflects the insertion

**Got:**
Apps crashes because of nil optional force unwrapping:
``` if (cardNumber?.count)! >= 7 || (cardNumber?.count)! < 4 {```

**Comment by orazz** [comment]
Why are u skipping this fields?

**Comment by airspeed** [comment]
@orazz I am not, customers are, but I unfortunately do not know the reason why they start editing from cvc field instead of starting from the card number, as it would be logic :/
It could be that they are speaker of some rtl language, but I have not data to prove this assumption.

**Comment by orazz** [comment]
ok. got it, update to version 0.1.7 check it.

**Comment by airspeed** [comment]
Works, thanks a lot!
