### ISSUE TITLE
This project doesn't compile under XCode 10

### ISSUE THREAD

**Issue by ima-tech** [orazz/CreditCardForm-iOS#30]
This project doesn't seem to be compiling under the new XCode 10. I get the following error: 

 The file “Pods-CreditCardFormTests.debug.xcconfig” couldn’t be opened because there is no such file. 

`(CreditCardForm-iOS-master/CreditCardForm.xcodeproj The file “Pods-CreditCardForm.debug.xcconfig” couldn’t be opened because there is no such file. (/CreditCardForm-iOS-master/Pods/Target Support Files/Pods-CreditCardForm/Pods-CreditCardForm.debug.xcconfig)`

**Comment by ima-tech** [comment]
Removing the Files under the Pods folder seem to resolve the issue with the new building system. But I am not sure yet of the implications of doing that.

**Comment by orazz** [comment]
Fixed 0.1.8
