### ISSUE TITLE
Card Brand Image not appearing 

### ISSUE THREAD

**Issue by joshualeon14** [orazz/CreditCardForm-iOS#33]
Hey I love this credit card form library for swift and I am trying to implement this into my app.  Everything works perfectly except the branding image on the card. I followed the instructions on how to install and add the form, but I can not get the brand icons to appear.  The icon appears in the text field but not on the card itself. Any suggestions or help?

**Comment by sagarsukode** [comment]
@joshualeon14: I have the same issue. Please give us a solution over it.

**Comment by ludivinefafournoux** [comment]
@joshualeon14 I have the same issue, still searching !
