### ISSUE TITLE
This project doesn't compile under XCode 10.1 and Swift 4.2

### ISSUE THREAD

**Issue by maikvinicius** [orazz/CreditCardForm-iOS#35]
This project does not seem to be compiling under the new XCode 10.1 and Swift 4.2. I get the following error:

![image](https://user-images.githubusercontent.com/16209118/49241683-b5585b00-f3ef-11e8-9c60-af472c5f460d.png)

**Comment by maikvinicius** [comment]
Updated: https://github.com/orazz/CreditCardForm-iOS/pull/36

**Comment by orazz** [comment]
Update to 0.1.9v
