### ISSUE TITLE
Amex CVC should be on the front

### ISSUE THREAD

**Issue by BenderNK** [orazz/CreditCardForm-iOS#37]
First of all, thank you so much for this library. It is awesome.

The issue I have seen is that when entering Amex card, the card image flips to simulate entering CVC number from the back. However, AMEX cards have their CVC numbers on the front. See the example from Stripe's own demo:

![side_by_side_comparison](https://user-images.githubusercontent.com/10276667/51843371-7142e300-22d8-11e9-817d-64037f5a0eef.png)

So the question is since you went through the trouble to make Stripe's lousy UI actually worth something, do you mind taking a look at this enhancement so that when a user enters an AMEX card, we don't actually flip but rather show the entering of CVC on the front of the card instead? Let me know what you think.
Thanks.

**Comment by orazz** [comment]
Hi, thanks. I'll consider your suggestion.

**Comment by orazz** [comment]
Update to 0.2.0v.
