### ISSUE TITLE
How to write card name using payment textfield?

### ISSUE THREAD

**Issue by hamzabinamin** [orazz/CreditCardForm-iOS#43]
The payment textfield only lets you write in the card number, expiration and cvc number. Is there a way to let the user write the card owner name as well?

@damarte @ima-tech @orazz @itaispector

**Comment by kemalsanli** [comment]
Yes you can do this like this.

creditCardView.cardHolderString = Helper.cardHolderName

When add new card button clicked i throw a uialertview that wants card holder name and redirects you to credit card form string.

**Comment by orazz** [comment]
[Example-Demo2](https://github.com/orazz/CreditCardForm-iOS/blob/master/Example/Demo2-CreditCardFormLibarary/Demo/ViewController.swift)
