### ISSUE TITLE
Changing card colors manually

### ISSUE THREAD

**Issue by hamzabinamin** [orazz/CreditCardForm-iOS#44]
Let's say I save a saved card that I know is of Visa or Mastercard brand. I can fetch the numeral data and show it in the card form but the card color doesn't change at all. It remains black.

I have tried the following:

` creditCardForm.colors[Brands.MasterCard.rawValue] = [hexStr(hexStr: "#ED495A", alpha: 1), hexStr(hexStr: "#8B1A2B", alpha: 1)]`

Is there a way to set the brand color and show the brand image (visa, mastercard etc) manually?

**Comment by orazz** [comment]
Update to 0.2.0 version
```creditCardForm.cardGradientColors[Brands.Visa.rawValue] = [UIColor.blue, UIColor.red]```
