### ISSUE TITLE
Credit Card Holder Name

### ISSUE THREAD

**Issue by cesarmtz93** [orazz/CreditCardForm-iOS#5]
is there a way i could add the option of capturing the card holders name?

**Comment by orazz** [comment]
[Demo 2](https://github.com/orazz/CreditCardForm-iOS/blob/master/Example/Demo2-CreditCardFormLibarary/Demo/ViewController.swift)

creditCardView.cardHolderString = "Name"

**Comment by cesarmtz93** [comment]
i meant it to be in the capturing form, is that possible?

**Comment by orazz** [comment]
@cesarmtz93 What do you mean by capturing?

**Comment by cesarmtzips93** [comment]
![img_3165](https://cloud.githubusercontent.com/assets/18411640/20888214/822163ec-bac3-11e6-85ee-5e4599455d2d.PNG)


Like this

**Comment by orazz** [comment]
No, it is impossible

**Comment by zahedul** [comment]
How to get cardName from card number ?

**Comment by titopalito** [comment]
You can use this code to create the card holder's field:

    func createCardHolderTextField() {
        let y = paymentTextField.frame.origin.y + 99
        let cardHolderTextField = UITextField()
        cardHolderTextField.frame = CGRect(x: 15, y: y, width: self.view.frame.size.width - 30, height: 44)
        cardHolderTextField.delegate = self
        paymentTextField.translatesAutoresizingMaskIntoConstraints = false
        paymentTextField.borderWidth = 0
        
        let border = CALayer()
        let width = CGFloat(1.0)
        border.borderColor = UIColor.darkGray.cgColor
        border.frame = CGRect(x: 0, y: paymentTextField.frame.size.height - width, width:  paymentTextField.frame.size.width, height: paymentTextField.frame.size.height)
        border.borderWidth = width
        cardHolderTextField.layer.addSublayer(border)
        cardHolderTextField.layer.masksToBounds = true
        view.addSubview(cardHolderTextField)
        
        NSLayoutConstraint.activate([
            cardHolderTextField.topAnchor.constraint(equalTo: paymentTextField.bottomAnchor, constant: 20),
            cardHolderTextField.centerXAnchor.constraint(equalTo: view.centerXAnchor),
            cardHolderTextField.widthAnchor.constraint(equalToConstant: self.view.frame.size.width-20),
            cardHolderTextField.heightAnchor.constraint(equalToConstant: 44)
            ])
        
        cardHolderTextField.placeholder = "CARD HOLDER"
        
    }

Dont forget to use the delegate methods in the `viewController` class

**Comment by titopalito** [comment]
> How to get cardName from card number ?

Reading a bit in the code, i just inserted:
```
 @IBInspectable
 public var brandImageName = ""
```
In the CreditCardFormView and assigned the type.name in line 430~433 after: 
```
self.brandImageView.image = UIImage(named: type.name, in: Bundle.currentBundle(), compatibleWith: nil)
```

**Comment by Nomieee** [comment]
creditCardView.cardHolderString = textField.text

for card Holder Name capture (User can enter Name in textField get Value in cardHolderString
