### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by lfarah** [orazz/CreditCardForm-iOS#7]
Hey, your library is really interesting.

The only problem I found was the ```README.md```, which lacks an ```Usage Section```
I created this [iOS Open source Readme Template](https://github.com/awesome-labs/iOS-readme-template) so you can take a look on how to easily create an ```Usage Section```
If you want, I can help you to organize the lib.

What are your thoughts? 😄

**Comment by orazz** [comment]
I think it's a good idea.  Feel free to submit a pull request.
