### ISSUE TITLE
Erro on publish app to AppStore

### ISSUE THREAD

**Issue by weibsons** [orazz/CreditCardForm-iOS#9]
When i try upload app to AppStore display this error. Refer to module CreditCardForm.

ERROR ITMS-90035: "Invalid Signature. Code object is not signed at all. Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level). Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a Simulator target. If you are certain your code signing settings are correct, choose "Clean All" in Xcode, delete the "build" directory in the Finder, and rebuild your release target. For more information, please consult https://developer.apple.com/library/ios/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html"

ERROR ITMS-90035: "Invalid Signature. Code object is not signed at all. Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level). Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a Simulator target. If you are certain your code signing settings are correct, choose "Clean All" in Xcode, delete the "build" directory in the Finder, and rebuild your release target. For more information, please consult https://developer.apple.com/library/ios/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html"

ERROR ITMS-90171: "Invalid Bundle Structure - The binary file '[my-app].app/Frameworks/CreditCardForm.framework/AKMaskFieldEvent.o' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."
ERROR ITMS-90171: "Invalid Bundle Structure - The binary file '[my-app].app/Frameworks/CreditCardForm.framework/AKMaskFieldEvent.o' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."

ERROR ITMS-90171: "Invalid Bundle Structure - The binary file '[my-app].app/Frameworks/CreditCardForm.framework/AKMaskFieldBlock.o' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."
ERROR ITMS-90171: "Invalid Bundle Structure - The binary file '[my-app].app/Frameworks/CreditCardForm.framework/AKMaskFieldBlock.o' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."
ERROR ITMS-90171: "Invalid Bundle Structure - The binary file '[my-app].app/Frameworks/CreditCardForm.framework/AKMaskFieldStatus.o' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."
ERROR ITMS-90171: "Invalid Bundle Structure - The binary file '[my-app].app/Frameworks/CreditCardForm.framework/AKMaskFieldStatus.o' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."

ERROR ITMS-90171: "Invalid Bundle Structure - The binary file '[my-app].app/Frameworks/CreditCardForm.framework/AKMaskFieldBlockCharacter.o' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."
ERROR ITMS-90171: "Invalid Bundle Structure - The binary file '[my-app].app/Frameworks/CreditCardForm.framework/AKMaskFieldBlockCharacter.o' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."

ERROR ITMS-90171: "Invalid Bundle Structure - The binary file '[my-app].app/Frameworks/CreditCardForm.framework/AKMaskField.o' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."
ERROR ITMS-90171: "Invalid Bundle Structure - The binary file '[my-app].app/Frameworks/CreditCardForm.framework/AKMaskField.o' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."

ERROR ITMS-90171: "Invalid Bundle Structure - The binary file '[my-app].app/Frameworks/CreditCardForm.framework/Utilities.o' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."
ERROR ITMS-90171: "Invalid Bundle Structure - The binary file '[my-app].app/Frameworks/CreditCardForm.framework/Utilities.o' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."

ERROR ITMS-90171: "Invalid Bundle Structure - The binary file '[my-app].app/Frameworks/CreditCardForm.framework/CreditCardFormView.o' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."
ERROR ITMS-90171: "Invalid Bundle Structure - The binary file '[my-app].app/Frameworks/CreditCardForm.framework/CreditCardFormView.o' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."

ERROR ITMS-90171: "Invalid Bundle Structure - The binary file '[my-app].app/Frameworks/CreditCardForm.framework/CreditCardValidationType.o' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."
ERROR ITMS-90171: "Invalid Bundle Structure - The binary file '[my-app].app/Frameworks/CreditCardForm.framework/CreditCardValidationType.o' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."

ERROR ITMS-90171: "Invalid Bundle Structure - The binary file '[my-app].app/Frameworks/CreditCardForm.framework/AKMaskFieldPatternCharacter.o' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."
ERROR ITMS-90171: "Invalid Bundle Structure - The binary file '[my-app].app/Frameworks/CreditCardForm.framework/AKMaskFieldPatternCharacter.o' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."

ERROR ITMS-90171: "Invalid Bundle Structure - The binary file '[my-app].app/Frameworks/CreditCardForm.framework/CreditCardValidator.o' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."
ERROR ITMS-90171: "Invalid Bundle Structure - The binary file '[my-app].app/Frameworks/CreditCardForm.framework/CreditCardValidator.o' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."

ERROR ITMS-90171: "Invalid Bundle Structure - The binary file '[my-app].app/Frameworks/CreditCardForm.framework/AKMaskFieldUtility.o' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."
ERROR ITMS-90171: "Invalid Bundle Structure - The binary file '[my-app].app/Frameworks/CreditCardForm.framework/AKMaskFieldUtility.o' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."

**Comment by orazz** [comment]
Please, update pod (to version CreditCardForm 0.0.7) and try again...It should work!

**Comment by orazz** [comment]
@weibsons  did you upload?

**Comment by varunmehta77** [comment]
I also got same error.
And also not able to install a version above 0.0.6.
It gives error when trying to install above version using pod.

**Comment by orazz** [comment]
@varunmehta77  What error did you get? show me screenshots...

**Comment by MustajabJafry** [comment]
I got the same error. My CreditCardForm pod version is updated. Here is the screenshot
![screen shot 2017-02-24 at 7 31 47 pm](https://cloud.githubusercontent.com/assets/23034100/23307170/69f49376-fac8-11e6-9038-121a4635b038.png)

**Comment by MustajabJafry** [comment]
My value for ALWAYS_EMBED_SWIFT_STANDARD-LIBRARIES is set to $(inherited).
I got this warning while installing pods.
Unable to read the license file `/Volumes/Untitled/CleaningMaster/Pods/CreditCardForm/LICENSE.md` for the spec `CreditCardForm (0.0.9)`

In my podfile:
pod ‘CreditCardForm’, '~> 0.0.8’
